package com.gultekinahmetabdullah.sirdas.viewmodels

import androidx.compose.ui.text.capitalize
import androidx.compose.ui.text.decapitalize
import androidx.compose.ui.text.intl.Locale
import androidx.lifecycle.LiveData
import androidx.lifecycle.MutableLiveData
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.google.firebase.firestore.FirebaseFirestore
import com.google.firebase.firestore.Query
import com.gultekinahmetabdullah.sirdas.classes.dataclasses.Book
import kotlinx.coroutines.launch
import kotlinx.coroutines.tasks.await

class BookViewModel : ViewModel() {

    private val db = FirebaseFirestore.getInstance()
    private val booksCollection = db.collection("books")

    private val _bookLiveData = MutableLiveData<Book?>()
    val bookLiveData: LiveData<Book?> get() = _bookLiveData

    private val _bookListLiveData = MutableLiveData<List<Book>>()
    val bookListLiveData: LiveData<List<Book>> get() = _bookListLiveData

    init {
        try {
            fetchAllBooks()
        } catch (e: Exception) {
            _bookListLiveData.value = emptyList()
            e.printStackTrace()
        }
    }

    // Fetch a single book by ID
    fun fetchBookById(id: Int) {
        viewModelScope.launch {
            booksCollection.whereEqualTo("id", id)
                .get()
                .addOnSuccessListener { documents ->
                    if (!documents.isEmpty) {
                        _bookLiveData.value = documents.first().toObject(Book::class.java)
                    } else {
                        _bookLiveData.value = null
                    }
                }
                .addOnFailureListener {
                    _bookLiveData.value = null
                }
        }
    }

    // Fetch all books
    fun fetchAllBooks() {
        viewModelScope.launch {
            booksCollection.get()
                .addOnSuccessListener { documents ->
                    val bookList = documents.map { it.toObject(Book::class.java) }
                    _bookListLiveData.value = bookList
                }
                .addOnFailureListener {
                    _bookListLiveData.value = emptyList()
                }
        }
    }

    // Add or update a book
    fun addOrUpdateBook(book: Book) {
        viewModelScope.launch {
            if (book.id.isEmpty()) {
                // Add new book with autogenerated ID
                booksCollection.add(book)
                    .addOnSuccessListener { documentReference ->
                        // Update the book with the generated ID
                        val updatedBook = book.copy(id = documentReference.id)
                        booksCollection.document(documentReference.id).set(updatedBook)
                            .addOnSuccessListener {
                                // Successfully added book with autogenerated ID
                                fetchAllBooks()
                            }
                            .addOnFailureListener {
                                // Handle failure
                            }
                    }
                    .addOnFailureListener {
                        // Handle failure
                    }
            } else {
                // Update existing book
                booksCollection.document(book.id)
                    .set(book)
                    .addOnSuccessListener {
                        // Successfully updated book
                        fetchAllBooks()
                    }
                    .addOnFailureListener {
                        // Handle failure
                    }
            }
        }
    }

    // Delete a book
    fun deleteBook(id: Int) {
        viewModelScope.launch {
            booksCollection.document(id.toString())
                .delete()
                .addOnSuccessListener {
                    // Successfully deleted book
                }
                .addOnFailureListener {
                    // Handle failure
                }
        }
    }

    // Update specific fields in a book
    fun updateBookFields(id: Int, updates: Map<String, Any>) {
        viewModelScope.launch {
            booksCollection.document(id.toString())
                .update(updates)
                .addOnSuccessListener {
                    // Successfully updated book fields
                }
                .addOnFailureListener {
                    // Handle failure
                }
        }
    }

    // Search books by title or author
    fun searchBooks(query: String, selectedBookFilter: String) {
        viewModelScope.launch {
                val list = booksCollection
                    .orderBy(selectedBookFilter.replace(" ", "").decapitalize(Locale.current))
                    .startAt(query)
                    .endAt(query + "\uf8ff")
                    .get().await()

            _bookListLiveData.value = list.toObjects(Book::class.java)
        }
    }

    // Filter books based on criteria (e.g., isFinished, rating)
    fun filterBooks(isFinished: Boolean? = null, minRating: Float? = null) {
        viewModelScope.launch {
            var query: Query = booksCollection

            if (isFinished != null) {
                query = query.whereEqualTo("isFinished", isFinished)
            }

            if (minRating != null) {
                query = query.whereGreaterThanOrEqualTo("rating", minRating)
            }

            query.get()
                .addOnSuccessListener { documents ->
                    val bookList = documents.map { it.toObject(Book::class.java) }
                    _bookListLiveData.value = bookList
                }
                .addOnFailureListener {
                    _bookListLiveData.value = emptyList()
                }
        }
    }
}
